[project]
name = "uaf_dasc_pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mykhaylo Shumko", email = "msshumko@alaska.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "asdf",
    "astropy",
    "certifi>=2026.1.4",
    "pillow",
    "matplotlib",
    "numpy",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
